# -*- coding: utf-8 -*-
"""brAIn_v02.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BHp2OHoDoNFXBslnb0PVUdesvk2xmlBE
"""

import requests

# Replace with your actual API key and external user ID
api_key = 'YVDHi9RwZsEzK0yfbdTBhZD39jNv5kvg'
external_user_id = '671b37db126b587457bd12b8'

# Step 1: Create Chat Session
create_session_url = 'https://api.on-demand.io/chat/v1/sessions'
create_session_headers = {
    'apikey': api_key
}
create_session_body = {
    "pluginIds": [],
    "externalUserId": external_user_id
}

# Make the request to create a chat session
response = requests.post(create_session_url, headers=create_session_headers, json=create_session_body)
response_data = response.json()

# Extract session ID from the response
session_id = response_data['data']['id']

# Step 2: Submit Query
submit_query_url = f'https://api.on-demand.io/chat/v1/sessions/{session_id}/query'
submit_query_headers = {
    'apikey': api_key
}
submit_query_body = {
    "endpointId": "predefined-openai-gpt4o",
    "query": "Explain the impact of reinforcement learning in stock trading applications.",
    "pluginIds": [
        "plugin-1712327325",
        "plugin-1713962163",
        "plugin-1729887207",
        "plugin-1726253762",
        "plugin-1728287833"
    ],
    "responseMode": "sync"
}

# Make the request to submit a query
query_response = requests.post(submit_query_url, headers=submit_query_headers, json=submit_query_body)
query_response_data = query_response.json()

# Print the response from the query submission
print(query_response_data)

